[package]
name = 'slixon-scores'
version = '0.9.6'
authors = ["Setheum Labs"]
edition = '2018'

[features]
default = ['std']
std = [
    'codec/std',
    'sp-runtime/std',
    'frame-support/std',
    'frame-system/std',
    'sp-std/std',
    'slixon-utils/std',
    'slixon-profiles/std',
    'slixon-profile-follows/std',
    'slixon-posts/std',
    'slixon-channels/std',
    'slixon-channel-follows/std',
    'slixon-reactions/std',
]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
# Local dependencies
slixon-posts = { default-features = false, path = '../posts' }
slixon-profile-follows = { default-features = false, path = '../profile-follows' }
slixon-profiles = { default-features = false, path = '../profiles' }
slixon-reactions = { default-features = false, path = '../reactions' }
slixon-channel-follows = { default-features = false, path = '../channel-follows' }
slixon-channels = { default-features = false, path = '../channels' }
slixon-utils = { default-features = false, path = '../utils' }

# Substrate dependencies
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }

[dev-dependencies]
sp-core = { default-features = false, version = '3.0.0' }
