[package]
authors = ['Setheum Labs']
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Unlicense'
name = 'setheum-runtime'
version = '0.9.6'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = '4.0.0'

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
smallvec = "1.4.0"
hex-literal = { optional = true, version = '0.3.1' }
serde = { features = ['derive'], optional = true, version = '1.0.119' }
serde_json = "1.0.60"
evm = { version = "0.26.0", optional = true, default-features = false }

# Substrate dependencies
frame-benchmarking = { default-features = false, optional = true, version = '3.0.0' }
frame-executive = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
frame-system-benchmarking = { default-features = false, optional = true, version = '3.0.0' }
frame-system-rpc-runtime-api = { default-features = false, version = '3.0.0' }
pallet-balances = { default-features = false, version = '3.0.0' }
pallet-grandpa = { default-features = false, version = '3.0.0' }
pallet-indices = { version = "3.0.0", default-features = false }
pallet-proxy = { version = "3.0.0", default-features = false }
pallet-randomness-collective-flip = { default-features = false, version = '3.0.0' }
pallet-scheduler = { version = "3.0.0", default-features = false }
pallet-sudo = { default-features = false, version = '3.0.0' }
pallet-timestamp = { default-features = false, version = '3.0.0' }
pallet-tips = { version = "3.0.0", default-features = false }
pallet-transaction-payment = { default-features = false, version = '3.0.0' }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = '3.0.0' }
pallet-treasury = { version = "3.0.0", default-features = false }
pallet-utility = { version = "3.0.0", default-features = false }
sp-api = { version = "3.0.0", default-features = false }
sp-application-crypto = { version = "3.0.0", default-features = false }
sp-block-builder = { version = "3.0.0", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
sp-inherents = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
sp-offchain = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-session = { version = "3.0.0", default-features = false }
sp-staking = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
sp-transaction-pool = { version = "3.0.0", default-features = false }
sp-version = { version = "3.0.0", default-features = false }
libsecp256k1 = { version = "0.6", default-features = false, optional = true }

# NPoS
pallet-session = { version = "3.0.0", features = ["historical"], default-features = false }
pallet-staking = { version = "3.0.0", default-features = false }
pallet-staking-reward-curve = { version = "3.0.0", default-features = false }
pallet-authorship = { version = "3.0.0", default-features = false }
pallet-babe = { version = "3.0.0", default-features = false }
sp-consensus-babe = { version = "0.9.0", default-features = false }
pallet-im-online = { version = "3.0.0", default-features = false }
pallet-offences = { version = "3.0.0", default-features = false }
sp-authority-discovery = { version = "3.0.0", default-features = false }
pallet-authority-discovery = { version = "3.0.0", default-features = false }

pallet-identity = { version = "3.0.0", default-features = false }


# Governance and others
pallet-bounties = { version = "3.0.0", default-features = false }
pallet-collective = { version = "3.0.0", default-features = false }
pallet-membership = { version = "3.0.0", default-features = false }
pallet-multisig = { version = "3.0.0", default-features = false }

# local dependencies
orml-authority = { path = "../../open-lib/authority", default-features = false }
orml-benchmarking = { path = "../../open-lib/benchmarking", default-features = false, optional = true }
orml-nft= { path = "../../open-lib/nft", default-features = false }
orml-oracle = { path = "../../open-lib/oracle", default-features = false }
orml-oracle-rpc-runtime-api = { path = "../../open-lib/oracle/rpc/runtime-api", default-features = false }
orml-tokens = { path = "../../open-lib/tokens", default-features = false }
orml-traits = { path = "../../open-lib/traits", default-features = false }

module-currencies = { path = "../../lib-serml/currencies", default-features = false }
module-dex = { path = "../../lib-serml/dex", default-features = false }
module-evm = { path = "../../lib-serml/evm", default-features = false }
module-evm-accounts = { path = "../../lib-serml/evm-accounts", default-features = false }
module-evm-bridge = { path = "../../lib-serml/evm-bridge", default-features = false }
module-evm-manager = { path = "../../lib-serml/evm-manager", default-features = false }
module-evm-rpc-runtime-api = { path = "../../lib-serml/evm/rpc/runtime_api",  default-features = false }
module-nft = { path = "../../lib-serml/nft", default-features = false }
module-prices = { path = "../../lib-serml/prices", default-features = false }
module-recovery = { path = "../../lib-serml/recovery", default-features = false }
setheum-renvm-bridge = { path = "../../lib-serml/renvm-bridge", default-features = false }
serp-treasury = { path = "../../lib-serml/serp-treasury", default-features = false }
serp-ocw = { path = "../../lib-serml/serp-ocw", default-features = false }
module-support = { path = "../../lib-serml/support", default-features = false }
module-transaction-payment = { path = "../../lib-serml/transaction-payment", default-features = false }
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
runtime-common = { path = "../common", default-features = false }


[dev-dependencies]
libsecp256k1 = "0.6"
hex = "0.4.0"
hex-literal = "0.3.1"


[features]
default = ['std']
std = [
	'codec/std',
	'serde',
	'frame-executive/std',
	'frame-support/std',
	'frame-system/std',
	'frame-system-rpc-runtime-api/std',
	"frame-benchmarking/std",
	'pallet-balances/std',
	'pallet-grandpa/std',
	"pallet-indices/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-proxy/std",
	'pallet-randomness-collective-flip/std',
	'pallet-sudo/std',
	"pallet-scheduler/std",
	'pallet-timestamp/std',
	'pallet-transaction-payment/std',
	'pallet-transaction-payment-rpc-runtime-api/std',
	"pallet-treasury/std",
	"pallet-utility/std",
	"pallet-bounties/std",
	"pallet-collective/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-authorship/std",
	"pallet-babe/std",
	"sp-consensus-babe/std",
	"sp-authority-discovery/std",
	"pallet-authority-discovery/std",
	"pallet-im-online/std",
	"pallet-offences/std",
	"pallet-identity/std",

	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	"orml-traits/std",
	"orml-tokens/std",
	"orml-authority/std",
	"orml-benchmarking/std",
	"orml-oracle-rpc-runtime-api/std",
	"orml-oracle/std",
	"orml-nft/std",

	"module-currencies/std",
	"serp-treasury/std",
	"serp-ocw/std",
	"module-dex/std",
	"module-evm/std",
	"module-evm-accounts/std",
	"module-evm-bridge/std",
	"module-evm-manager/std",
	"module-nft/std",
	"module-prices/std",
	"module-transaction-payment/std",
	"module-support/std",

	"primitives/std",

	"runtime-common/std",

	"module-evm-rpc-runtime-api/std",

	"setheum-renvm-bridge/std",
]
with-ethereum-compatibility = [
	"evm",
	"module-evm/with-ethereum-compatibility",
	"runtime-common/with-ethereum-compatibility",
]
runtime-benchmarks = [
	'hex-literal',
	"libsecp256k1/hmac",

	'frame-benchmarking',
	'frame-support/runtime-benchmarks',
	'frame-system-benchmarking',
	'frame-system/runtime-benchmarks',
	'pallet-balances/runtime-benchmarks',
	'pallet-timestamp/runtime-benchmarks',
	'sp-runtime/runtime-benchmarks',

	"orml-benchmarking",
	"orml-authority/runtime-benchmarks",

	"pallet-collective/runtime-benchmarks",

	"serp-treasury/runtime-benchmarks",
	"module-dex/runtime-benchmarks",
]
