[package]
name = 'profiles-rpc'
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

[dependencies.serde]
optional = true
features = ['derive']
version = '1.0.119'

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
jsonrpc-core = '15.0.0'
jsonrpc-core-client = '15.0.0'
jsonrpc-derive = '15.0.0'

# Local dependencies
slixon-profiles = { default-features = false, path = '..' }
slixon-utils = { default-features = false, path = '../../utils' }

# Custom Runtime API
profiles-runtime-api = { default-features = false, path = 'runtime-api' }

# Substrate dependencies
sp-api = { default-features = false, version = '3.0.0' }
sp-blockchain = { default-features = false, version = '3.0.0' }
sp-rpc = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
  'serde',
  'sp-runtime/std',
  'sp-api/std',
  'profiles-runtime-api/std',
  'slixon-profiles/std',
]
