[package]
name = "module-support"
version = "0.7.3"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
impl-trait-for-tuples = "0.1.3"
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-runtime = { version = '3.0.0', default-features = false }
frame-support = { version = '3.0.0', default-features = false }
sp-std = { version = '3.0.0', default-features = false }
sp-core = { version = '3.0.0', default-features = false }
sp-io = { version = '3.0.0', default-features = false }

permissions = { package = "slixon-permissions", default-features = false, path = '../permissions' }
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
utils = { package = "slixon-utils", default-features = false, path = '../utils' }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-runtime/std",
	"sp-core/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"permissions/std",
	"primitives/std",
	"utils/std",
]
