[package]
name = "module-ecdp-core"
version = "0.9.81-dev"
authors = ["Setheum Labs"]
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-runtime = { workspace = true }
sp-core = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-std = { workspace = true }
module-ecdp-ussd-engine = { workspace = true }
module-ecdp-ussd-loans = { workspace = true }
module-support = { workspace = true }
primitives = { workspace = true }

[dev-dependencies]
sp-io = { workspace = true, features = ["std"] }
sp-core = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
orml-currencies = { workspace = true, features = ["std"] }
orml-traits = { workspace = true, features = ["std"] }
orml-tokens = { workspace = true, features = ["std"] }
module-ecdp-ussd-treasury = { workspace = true, features = ["std"] }
module-evm-accounts = { workspace = true, features = ["std"] }
module-evm = { workspace = true, features = ["std"] }
module-evm-bridge = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	"module-ecdp-ussd-engine/std",
	"parity-scale-codec/std",
	"frame-support/std",
	"frame-system/std",
	"module-ecdp-ussd-loans/std",
	"primitives/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"module-support/std",
]
try-runtime = [
	"module-ecdp-ussd-engine/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"module-ecdp-ussd-loans/try-runtime",
]
