// بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم

// This file is part of Setheum.

// Copyright (C) 2019-Present Setheum Labs.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for module_vk_storage
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-12-13, STEPS: `20`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("chainspec.json"), DB CACHE: 1024

// Executed Command:
// target/release/setheum-node
// benchmark
// pallet
// --chain=dev
// --pallet=module_vk_storage
// --extrinsic=*
// --steps=20
// --repeat=5
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./blockchain/modules/vk-storage/src/weights.rs
// --template=.maintain/module-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for module_vk_storage.
pub trait WeightInfo {
    fn store_key(key_length: u32) -> Weight;
}

impl<I: BenchmarkInfo> WeightInfo for I {
    fn store_key(key_length: u32) -> Weight {
        <I as BenchmarkInfo>::store_key(key_length)
    }
}

/// Benchmark results for module_vk_storage.
trait BenchmarkInfo {
    fn store_key(l: u32, ) -> Weight;
}

/// Weights for module_vk_storage using the Substrate node and recommended hardware.
pub struct SetheumWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> BenchmarkInfo for SetheumWeight<T> {
    // Storage: `VkStorage::VerificationKeys` (r:0 w:1)
    // Proof: `VkStorage::VerificationKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `l` is `[1, 10000]`.
    fn store_key(l: u32, ) -> Weight {
        // Minimum execution time: 8_597 nanoseconds.
        Weight::from_parts(9_536_460_u64, 0)
            // Standard Error: 54
            .saturating_add(Weight::from_parts(1_123_u64, 0).saturating_mul(l as u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

// For backwards compatibility and tests
impl BenchmarkInfo for () {
    // Storage: `VkStorage::VerificationKeys` (r:0 w:1)
    // Proof: `VkStorage::VerificationKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `l` is `[1, 10000]`.
    fn store_key(l: u32, ) -> Weight {
        // Minimum execution time: 8_597 nanoseconds.
        Weight::from_parts(9_536_460_u64, 0)
            // Standard Error: 54
            .saturating_add(Weight::from_parts(1_123_u64, 0).saturating_mul(l as u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
