[package]
name = "open-grant-rpc"
version = "0.0.1"
edition = "2018"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = "A pallet that demonstrates simple RPC for summing numbers"
license = "GPL-3.0-or-later"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"
serde = { version = "1.0.119", features = ["derive"], optional = true }

# Substrate packages

sp-api = { version = '3.0.0', default-features = false }
sp-blockchain = { version = '3.0.0', default-features = false}
sp-rpc = { version = '3.0.0', default-features = false}
sp-runtime = { version = '3.0.0', default-features = false}
sp-std = { default-features = false, version = '3.0.0' }

# local packages
open-grant-runtime-api = { version = "0.0.1", path = "../runtime-api", default-features = false }
pallet-open-grant = { version = "0.0.1", path = "../", default-features = false }

[features]
default = ["std"]
std = [
  "serde",
  "sp-api/std",
  "sp-runtime/std",
  "open-grant-runtime-api/std",
  "pallet-open-grant/std",
]
