[package]
name = 'slixon-posts'
version = '0.9.6'
authors = ["Setheum Labs"]
edition = '2018'

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-std/std',
    'module-support/std',
    'slixon-permissions/std',
    'slixon-channel-follows/std',
    'slixon-channels/std',
    'slixon-utils/std',
]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { features = ['derive'], optional = true, version = '1.0.119' }
impl-trait-for-tuples = '0.1.3'

# Local dependencies
module-support = { default-features = false, path = '../support' }
slixon-permissions = { default-features = false, path = '../permissions' }
slixon-channel-follows = { default-features = false, path = '../channel-follows' }
slixon-channels = { default-features = false, path = '../channels' }
slixon-utils = { default-features = false, path = '../utils' }

# Substrate dependencies
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }
