[package]
name = "setheum-evm-rpc-runtime-api"
version = "1.2.2"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "v3.0.0", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "v3.0.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "v3.0.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "v3.0.0", default-features = false }
ethereum-types = { version = "0.11", default-features = false }
primitives = { package = "setheum-primitives", path = "../../../../../primitives", default-features = false }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"sp-api/std",
	"sp-std/std",
	"sp-core/std",
	"ethereum-types/std",
	"primitives/std",
]
