[package]
name = "module-currencies-runtime-api"
version = "0.9.81"
authors = ["Setheum Labs"]
edition = "2021"

[dependencies]
sp-runtime = { workspace = true }
sp-api = { workspace = true }
sp-std = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"sp-api/std",
	"sp-std/std",
	"sp-core/std",
]
