[package]
name = 'posts-runtime-api'
version = '0.9.6'
authors = ["Setheum Labs"]
edition = '2018'

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { features = ['derive'], optional = true, version = '1.0.119' }

# Local dependencies
slixon-posts = { default-features = false, path = '../..' }
slixon-utils = { default-features = false, path = '../../../utils' }

# Substrate dependencies
sp-api = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
	'serde',
	'sp-api/std',
	'sp-std/std',
	'sp-runtime/std',
	'slixon-utils/std',
	'slixon-posts/std',
]
