[package]
name = "setheum-evm-manager"
version = "1.2.2"
authors = ["Setheum-Labs"]
edition = "2018"

[dependencies]
serde = { version = "1.0.124", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }

primitives = { package = "setheum-primitives", path = "../../../primitives", default-features = false }
setheum-support = { package = "setheum-support", path = "../../support", default-features = false }

[dev-dependencies]
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
orml-currencies = { path = "../../../lib-openrml/currencies" }
orml-tokens = { path = "../../../lib-openrml/tokens" }
orml-traits = { path = "../../../lib-openrml/traits" }
orml-utilities = { path = "../../../lib-openrml/utilities" }
setheum-evm = { path = "../evm" }
setheum-evm-bridge = { path = "../evm-bridge" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"primitives/std",
	"setheum-support/std",
]
try-runtime = ["frame-support/try-runtime"]
