[package]
name = "setheum-cli"
version = "0.8.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
log = "0.4.8"
structopt = "0.3.8"
codec = { package = "parity-scale-codec", version = "2.0.0" }

# Substrate dependencies
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", optional = true }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", optional = true }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", optional = true }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", optional = true }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", optional = true }

# local dependencies
inspect = { package = "setheum-inspect", path = "../../inspect" }
service = { package = "setheum-service", path = "../service", default-features = false, optional = true }

[build-dependencies]
orml-build-script-utils = { path = "../../lib-openrml/build-script-utils"}

[features]
default = [ "wasmtime", "cli" ]
wasmtime = [ "sc-cli/wasmtime" ]
cli = [
	"service",
	"sp-core",
	"sc-cli",
	"sc-service",
	"frame-benchmarking-cli",
	"try-runtime-cli",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
with-newrome-runtime = [
	"try-runtime-cli",
	"service/with-newrome-runtime",
]
with-setheum-runtime = [
	"service/with-setheum-runtime",
]
with-all-runtime = [
	"with-newrome-runtime",
	"with-setheum-runtime",
	"service/with-all-runtime",
]
