[package]
name = 'posts-rpc'
version = '0.9.6'
authors = ["Setheum Labs"]
edition = '2018'

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { features = ['derive'], optional = true, version = '1.0.119' }

jsonrpc-core = '15.0.0'
jsonrpc-core-client = '15.0.0'
jsonrpc-derive = '15.0.0'

# Local dependencies
slixon-posts = { default-features = false, path = '..' }
slixon-utils = { default-features = false, path = '../../utils' }

# Custom Runtime API
posts-runtime-api = { default-features = false, path = 'runtime-api' }

# Substrate dependencies
sp-api = { default-features = false, version = '3.0.0' }
sp-blockchain = { default-features = false, version = '3.0.0' }
sp-rpc = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
  'serde',
  'sp-runtime/std',
  'sp-api/std',
  'posts-runtime-api/std',
  'slixon-utils/std',
  'slixon-posts/std',
]
